services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=esportsclash'
      - 'POSTGRES_PASSWORD=esportsclash'
      - 'POSTGRES_USER=esportsclash'
    ports:
      - '4011:5432'
